POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "testausjee", 
"author": "Maximilian Aux-Haut",
"url": "http://maximilian-aux-haut-provence.blogger.fi/conquerfear/",
"userId": "64d7448b70ad65a7906a03cf"
}