POST http://localhost:3003/api/blogs
Content-Type: application/json

{
        "title": "React patterns",
        "author": "Michael Chans",
        "url": "https://reactpatterns.com/",
        "likes": 7,
        "userId": "64eca4ffa76fe98096fa9e33"
}